### PR TITLE
Move the options on commands to front of args. Added tests.

### PR DESCRIPTION
**Pull request by matthewpersico**
README.md
o Version update, api change note.

kvstore.sh
o All commands that take options now have their options moved to the
  front of their command arg list.

_kvstore_lock_then():
  o Remove useless lock check.

_kvstore_nonatomic_mv():
  o Option processing for --force added, tmp file renamed for clarity.

_kvstore_nonatomic_rm():
  o tmp file renamed for clarity.

_kvstore_nonatomic_set():
  o tmp file renamed for clarity.

_kvstore_ns_check():
  o Added to replace inline check.

kvstore():
  o list as alias for ls

kvstore_dump():
  o --verbose added to print kv store name before data, --raw for a quick
    dump, default is to print something prettier, with arrows.

kvstore_mv():
  o Added processing for forcing an overwrite of existing key.

kvstore_shellinit():
  o Added new commands to completion list.

kvstore_usage():
  o Do not need to echo the command we are usaging.

testing.sh
o Run some tests to prevent regressions.

testresults
o The results of running testing.sh to compare against future updates.

### CODE REVIEW

**Comment by ccarpita** [comment]
👍 All of this looks great.  Also thanks for writing tests!  When I get a chance I'll setup a CI system to do this and stylecheck.

**Comment by matthewpersico** [comment]
Oh don't thank me. I was about to commit it all when I decided to do one final code review because I hadn't touched it in so long. I discovered that I had implemented the options move in the caller functions, but the the CALLED functions. I wrote those test to cover my own ass! LOL!

And now that you have accepted this last pull, I can register the package at work and use it there, replacing my own store that uses sqlite3 as a backing, so I don't need to have sqlite3 on all machines to make key value stores work.

One more thing - you mention a bpkg for this. Have you updated that bpkg with the lastest code?

**Comment by ccarpita** [comment]
I believe that bpkg is sourced using master of this particular repository, but I can take a look at their current repository config.

**Comment by matthewpersico** [comment]
Closes #6 #8 #9 #10

**Comment by matthewpersico** [comment]
I tried a couple of times to add comments to this PR or the four open issues to try and close the open issues, but I'm either doing it wrong, doing it too late (PR has been accepted) or I am not the repo owner. I believe the this PR closes #6 #8 #9 and #10. You might want to close them yourself.

BTW I have successfully integrated kvstore into my development environment, replacing my sqlite3 based versions with your code via a few simple search and replaces. Works like a charm.

Thanks again!

**Comment by ccarpita** [comment]
@matthewpersico since you are finding time to knock out issues these days, I have made you a collaborator, so you should have push access and ability to change issue details.  Thanks for being such a strong contributor!

**Comment by matthewpersico** [comment]
You're welcome.

**Comment by amper5and** [comment]
@matthewpersico @ccarpita Thank you both for your work on this useful utility! I use it everyday.

**Pull request merged**
